apcrshr/apcrshr_site/Areas/Administrator/Controllers/AdminUserController.cs
using Site.Core.DataModel.Enum;
using Site.Core.DataModel.Model;
using Site.Core.DataModel.Response;
using Site.Core.Repository;
using Site.Core.Repository.Repository;
using Site.Core.Service.Contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using apcrshr_site.Filters;
using Site.Core.Service.Implementation;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using apcrshr_site.Helper;
using System.IO.Packaging;
using System.IO.Compression;


namespace apcrshr_site.Areas.Administrator.Controllers
{
    public class AdminUserController : Controller
    {
        private IUserService _userService;
        private IMainScholarshipService _mainScholarshipService;
        private IYouthScholarshipService _youthScholarshipService;
        private IExperienceService _experienceService;
        private IEducationService _educationService;
        private ITrainingService _trainingService;
        private ILeaderShipService _leadershipService;
        private IPublicationService _publicationService;
        private IUserSubmissionService _userSubmissionService;
        private IMailingAddressService _mailingAddressService;
        private IPaymentService _paymentService;
        private ILogisticSheduleService _logisticService;

        public static readonly string SCHOLARSHIP_NOT_AVAILABLE = "Scholarship not available";
        public static readonly string SCHOLARSHIP_MAIN_TITLE = "Main scholarship";
        public static readonly string SCHOLARSHIP_YOUTH_TITLE = "Youth scholarship";

        public AdminUserController()
        {
            ViewBag.CurrentNode = "AdminMember";
            this._userService = new UserService();
            this._mainScholarshipService = new MainScholarshipService();
            this._youthScholarshipService = new YouthScholarshipService();
            this._experienceService = new ExperienceService();
            this._educationService = new EducationService();
            this._trainingService = new TrainingService();
            this._leadershipService = new LeaderShipService();
            this._publicationService = new PublicationService();
            this._userSubmissionService = new UserSubmissionService();
            this._mailingAddressService = new MailingAddressService();
            this._paymentService = new PaymentService();
            this._logisticService = new LogisticSheduleService();
        }

        [SessionFilter]
        [AuthorizationFilter]
        public ActionResult Index()
        {
            FindAllItemReponse<UserModel> response = _userService.GetUsers();
            if (response.Items == null)
            {
                response.Items = new List<UserModel>();
            }
            return View(response.Items);
        }

        [SessionFilter]
        [AuthorizationFilter]
        [HttpGet]
        public ActionResult UpdateUser(string userId)
        {
            FindItemReponse<UserModel> response = _userService.FindUserByID(userId);
            if (response.ErrorCode != 0)
            {
                ViewBag.Message = new BaseResponse { ErrorCode = response.ErrorCode, Message = response.Message };
            }
            return View(response.Item);
        }

        [SessionFilter]
        [AuthorizationFilter]
        [HttpGet]
        public ActionResult ViewUser(string userId)
        {
            //Get user information
            FindItemReponse<UserModel> response = _userService.FindUserByID(userId);

            //Find logistic
            FindItemReponse<LogisticScheduleModel> logisticResponse = _logisticService.FindByUserID(userId);
            if (logisticResponse.Item != null)
            {
                ViewBag.Logistic = logisticResponse.Item;
            }

            //Find mailing
            FindAllItemReponse<MailingAddressModel> mailingResponse = _mailingAddressService.FindMailingAddressByUser(userId);
            if (mailingResponse.Items != null && mailingResponse.Items.Count > 0)
            {
                ViewBag.Mailing = mailingResponse.Items[0];
            }

            //Find abstract
            FindAllItemReponse<UserSubmissionModel> abstractResponse = _userSubmissionService.FindByUserID(userId);
            ViewBag.Abstracts = abstractResponse.Items;

            //Find main scholarship by userID
            FindAllItemReponse<MainScholarshipModel> mainScholarshipReponse = _mainScholarshipService.FindByUserID(userId);
            if (mainScholarshipReponse.Items != null)
            {
                ViewBag.MainScholarship = mainScholarshipReponse.Items;
                ViewBag.ScholarshipTitleMain = SCHOLARSHIP_MAIN_TITLE;
            }

            //Find youth scholarship by userID
            FindItemReponse<YouthScholarshipModel> youthScholarshipResponse = _youthScholarshipService.FindByUserID(userId);
            if (youthScholarshipResponse.Item != null)
            {
                ViewBag.YouthScholarship = youthScholarshipResponse.Item;
                ViewBag.ScholarshipTitleYouth = SCHOLARSHIP_YOUTH_TITLE;

                //Find working experience
                FindAllItemReponse<ExperienceModel> experienceResponse = _experienceService.FindByscholarshipID(youthScholarshipResponse.Item.YouthScholarshipID);
                ViewBag.Experiences = experienceResponse.Items;

                //Find education
                FindAllItemReponse<EducationModel> educationResponse = _educationService.FindByscholarshipID(youthScholarshipResponse.Item.YouthScholarshipID);
                ViewBag.Educations = educationResponse.Items;

                //Find training
                FindAllItemReponse<TrainingModel> trainingResponse = _trainingService.FindByscholarshipID(youthScholarshipResponse.Item.YouthScholarshipID);
                ViewBag.Trainings = trainingResponse.Items;

                //Find leadership
                FindAllItemReponse<LeaderShipModel> leadershipResponse = _leadershipService.FindByscholarshipID(youthScholarshipResponse.Item.YouthScholarshipID);
                ViewBag.Leaderships = leadershipResponse.Items;

                //Find publication
                FindAllItemReponse<PublicationModel> publicationResponse = _publicationService.FindByscholarshipID(youthScholarshipResponse.Item.YouthScholarshipID);
                ViewBag.Publications = publicationResponse.Items;
            }

            //Find payment
            FindAllItemReponse<PaymentModel> paymentResponse = _paymentService.FindByUserID(userId);
            if (paymentResponse.Items != null)
            {
                ViewBag.Payments = paymentResponse.Items;
            }

            return View(response.Item);
        }

        [HttpPost]
        public JsonResult SaveLogisticInfo(LogisticScheduleModel logistic)
        {
            if (!string.IsNullOrEmpty(logistic.LogisticID))
            {
                var response = _logisticService.Update(logistic);
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            else
            {
                logistic.LogisticID = Guid.NewGuid().ToString();
                logistic.CreatedDate = DateTime.Now;
                var response = _logisticService.Create(logistic);
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [SessionFilter]
        public ActionResult CreatePayment(string UserId)
        {
            return View();
        }

        [HttpPost]
        public JsonResult SavePayment(PaymentModel payment)
        {
            var sessionId = this.Session["SessionID"].ToString();
            IUserSessionRepository userSessionRepository = RepositoryClassFactory.GetInstance().GetUserSessionRepository();
            UserSession userSession = userSessionRepository.FindByID(sessionId);

            if (userSession == null)
            {
                return Json(new { errorCode = (int)ErrorCode.Redirect, message = Resources.AdminResource.msg_sessionInvalid }, JsonRequestBehavior.AllowGet);
            }

            payment.PaymentID = Guid.NewGuid().ToString();
            payment.CreatedBy = userSession.UserID;
            payment.CreatedDate = DateTime.Now;
            InsertResponse response = _paymentService.Create(payment);
            return Json(new { ErrorCode = response.ErrorCode, Message = response.Message }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult DeletePayment(string paymentID)
        {
            BaseResponse response = _paymentService.Delete(paymentID);
            return Json(new { ErrorCode = response.ErrorCode, Message = response.Message }, JsonRequestBehavior.AllowGet);
        }

        [SessionFilter]
        [AuthorizationFilter]
        [HttpGet]
        public ActionResult UpdatePayment(string paymentID)
        {
            FindItemReponse<PaymentModel> response = _paymentService.FindByID(paymentID);
            return View(response.Item);
        }

        [SessionFilter]
        [HttpPost]

        public JsonResult SaveUpdatePayment(PaymentModel payment)
        {
            var sessionId = this.Session["SessionID"].ToString();
            IUserSessionRepository userSessionRepository = RepositoryClassFactory.GetInstance().GetUserSessionRepository();
            UserSession userSession = userSessionRepository.FindByID(sessionId);

            if (userSession == null)
            {
                return Json(new { errorCode = (int)ErrorCode.Redirect, message = Resources.AdminResource.msg_sessionInvalid }, JsonRequestBehavior.AllowGet);
            }

            payment.UpdatedBy = userSession.UserID;
            BaseResponse response = _paymentService.Update(payment);

            return Json(new { errorCode = response.ErrorCode, message = response.Message }, JsonRequestBehavior.AllowGet);
        }

        [SessionFilter]
        [AuthorizationFilter]

apcrshr/apcrshr_site/Areas/Administrator/Views/AdminUser/CreatePayment.cshtml
@using apcrshr_site.Helper
@model Site.Core.DataModel.Model.PaymentModel
@{
    ViewBag.Title = "Thêm Payment";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3>
                    <i class="fa fa-edit"></i>Thêm Payment
                </h3>
            </div>
            <div class="box-content nopadding">
                @using (Html.BeginForm("SavePayment", "AdminUser", FormMethod.Post, new { @class = "form-horizontal form-bordered", id = "frmSavePayment" }))
                {
                    <div class="form-group">
                        <label for="textfield" class="control-label col-sm-2">Loại thanh toán</label>
                        <div class="col-sm-10">
                            <select name="PaymentType" id="PaymentType" data-rule-required="true">
                                <option value="International delegates">International delegates</option>
                                <option value="Vietnamese delegate">Vietnamese delegate</option>
                                <option value="International youth">International youth</option>
                                <option value="Vietnamese youth">Vietnamese youth</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.PaymentType)
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="textfield" class="control-label col-sm-2">Merch Reference</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.MerchRef, new { @class = "form-control", @id = "MerchRef" })
                            @Html.ValidationMessageFor(model => model.MerchRef)
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="textfield" class="control-label col-sm-2">Số tiền <span class="validation-span-required">(*)</span></label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.Amount, new { @class = "form-control", @id = "Amount" })
                            @Html.ValidationMessageFor(model => model.Amount)
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="textfield" class="control-label col-sm-2">Trạng thái <span class="validation-span-required">(*)</span></label>
                        <div class="col-sm-10">
                            <select class="form-control" id="Status" name="Status">
                                <option value="0">Completed</option>
                                <option value="3">Cash</option>
                                <option value="6">Onsite payment</option>
                                <option value="5">Bank Transfer</option>
                                <option value="4">Free Registration</option>
                                <option value="1">Pending</option>
                                <option value="2">Error</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-actions col-sm-offset-2 col-sm-10">
                        <button type="button" onclick="submitForm()" class="btn btn-primary">Lưu Thông Tin</button>
                        <a href='@Url.Action("Index")' class="btn btn-info">Hủy Bỏ</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script>
    function submitForm() {
        if (!validateForm()) {
            bootbox.alert("Cần phải nhập dữ liệu những trường bắt buộc.", function () {
                bootbox.hideAll();
            });
            return false;
        }

        $.blockUI({ message: $('#spinner') });
        var formData = new FormData();
        formData.append("UserID", appUtil.utility.getURLParameter("UserId"));
        formData.append("PaymentType", $("#PaymentType").val());
        formData.append("MerchRef", $("#MerchRef").val());
        formData.append("Amount", $("#Amount").val());
        formData.append("Status", $("#Status").find(":selected").val());

        $.ajax({
            type: "POST",
            url: '@Url.Action("SavePayment", "AdminUser")',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false,
            success: function (response) {
                $.unblockUI();
                bootbox.alert(response.Message, function () {
                    bootbox.hideAll();
                });
                //Timeout
                if (response.ErrorCode == 2) {
                    window.location = "/Administrator/AdminHome/Login";
                }
            },
            error: function (error) {
                $.unblockUI();
                bootbox.alert(error, function () {
                    bootbox.hideAll();
                });
            }
        });
    }

    function validateForm() {
        if ($("#MerchRef").val() == null || $("#MerchRef").val() == "") {
            $("#MerchRef").focus();
            return false;
        }
        if ($("#Amount").val() == null || $("#Amount").val() == "") {
            $("#Amount").focus();
            return false;
        }
        return true;
    }
</script>

apcrshr/apcrshr_site/Areas/Administrator/Views/AdminUser/UpdateAbstract.cshtml
@model Site.Core.DataModel.Model.UserSubmissionModel
@{
    ViewBag.Title = "Cập Nhật Abstract Submission";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <!--Alert-->
        @if (ViewBag.Message != null)
        {
            Site.Core.DataModel.Response.BaseResponse responseMsg = (Site.Core.DataModel.Response.BaseResponse)ViewBag.Message;
            <br />
            <div class="alert @(responseMsg.ErrorCode == (int)Site.Core.DataModel.Enum.ErrorCode.None ? " alert-info" : " alert-danger")"><a class="close" data-dismiss="alert" href="#">×</a><strong></strong> @responseMsg.Message</div>
        }

        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3>
                    <i class="fa fa-edit"></i>Cập Nhập Người Dùng
                </h3>
            </div>
            <div class="box-content">
                @using (Ajax.BeginForm("SaveUpdateAbstract", "AdminUser", new AjaxOptions
                {
                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "POST",
                    OnFailure = "OnAbstractFailure",
                    OnSuccess = "OnAbstractSuccess",
                    OnBegin = "OnBeginSubmit"
                    }, new { @class = "form-horizontal form-validate", id = "frmAbstract" }))
                {
                    @Html.HiddenFor(m => m.SubmitID)
                    @Html.HiddenFor(m => m.UserID)
                    <div class="form-group">
                        <label for="Title" class="control-label col-sm-2">Submission Number</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(Model => Model.SubmissionNumber, new Dictionary<string, object> {
                                { "class", "form-control" },
                                { "data-rule-required", "true" }
                            })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="FullName" class="control-label col-sm-2">Trạng thái abstract</label>
                        <div class="col-sm-10">
                            @Html.DropDownList("Status", apcrshr_site.Helper.DataHelper.GetInstance().GetAbstractStatusForDropdown(), new Dictionary<string, object> {
                                { "class", "form-control" },
                                { "data-rule-required", "true" }
                            })
                        </div>
                    </div>
                    <div class="form-actions col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Lưu Thông Tin</button>
                        <a href='@Url.Action("Index")' class="btn btn-info">Hủy Bỏ</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    jQuery(document).ready(function () {
        $("#frmAbstract").validate();
    });

    function OnBeginSubmit() {
        if (!$("#frmAbstract").valid()) {
            return false;
        }
        $.blockUI({ message: $('#spinner') });
    }

    function OnAbstractFailure() {
        $.unblockUI();
    }

    function OnAbstractSuccess(response) {
        //Timeout
        if (response.ErrorCode == 2) {
            window.location = '@Url.Action("Login", "User")';
        }
        if (response.ErrorCode == "1") {
            $.unblockUI();
            bootbox.alert(response.Message, function () {
                bootbox.hideAll();
            });
        } else if (response.ErrorCode == "0") {
            $.unblockUI();
            bootbox.alert(response.Message, function () {
                bootbox.hideAll();
            });
        }
    }
</script>

apcrshr/apcrshr_site/Areas/Administrator/Views/AdminUser/UpdateMainScholarship.cshtml
@model Site.Core.DataModel.Model.MainScholarshipModel
@using apcrshr_site.Helper
@{
    ViewBag.Title = "Update Main Scholarship";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-sm-12">
        <!--Alert-->
        @if (ViewBag.Message != null)
        {
            Site.Core.DataModel.Response.BaseResponse responseMsg = (Site.Core.DataModel.Response.BaseResponse)ViewBag.Message;
            <br />
            <div class="alert @(responseMsg.ErrorCode == (int)Site.Core.DataModel.Enum.ErrorCode.None ? " alert-info" : " alert-danger")"><a class="close" data-dismiss="alert" href="#">×</a><strong></strong> @responseMsg.Message</div>
        }

        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3>
                    <i class="fa fa-edit"></i>Cập Nhập Người Dùng
                </h3>
            </div>
            <div class="box-content nopadding">
                @using (Html.BeginForm("SaveUpdateMainScholarship", "AdminUser", FormMethod.Post, new { @class = "form-horizontal form-bordered" }))
                {
                    
                    @Html.HiddenFor(m => m.UserID)
                    @Html.HiddenFor(m => m.RegistrationNumber)
                    @Html.HiddenFor(m => m.ScholarshipID)
                    <div class="form-group">
                        <label for="RegistrationNumber" class="control-label col-sm-2">Registration number</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.RegistrationNumber, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="SubmissionNumber" class="control-label col-sm-2">Abstract submission number</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.SubmissionNumber, new { @class = "form-control", @id = "SubmissionNumber" })
                        </div>
                    </div>
                    <div class="box-title">
                        <h3>
                            <i class="fa fa-check"></i>
                            WORKING EXPERIENCE
                        </h3>
                    </div>
                    <div class="form-group">
                        <label for="Organization" class="control-label col-sm-2">Current organization</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.Organization, new { @class = "form-control", @id = "Organization" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Position" class="control-label col-sm-2">Position</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.Position, new { @class = "form-control", @id = "Position" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="DurationOfWork" class="control-label col-sm-2">Duration of work</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.DurationOfWork, new { @class = "form-control", @id = "DurationOfWork" })
                            <small>(years)</small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Responsibility" class="control-label col-sm-2">Responsibility relating to Reproductive and Sexual Health and Rights</label>
                        <div class="col-sm-10">
                            @Html.TextAreaFor(model => model.Responsibility, new { @class = "form-control", @rows = "6", @id = "Responsibility" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ReasonScholarship" class="control-label col-sm-2">Why should we provide you a scholarship?</label>
                        <div class="col-sm-10">
                            @Html.TextAreaFor(model => model.ReasonScholarship, new { @class = "form-control", @rows = "6", @id = "ReasonScholarship" })
                        </div>
                    </div>
                    <div class="box-title">
                        <h3>
                            <i class="fa fa-check"></i>
                            ABSTRACT SUBMISSION
                        </h3>
                    </div>
                    <div class="form-group">
                        <label for="Locked" class="control-label col-sm-2">Have you submitted at least 1 abstract for the conference</label>
                        <div class="col-sm-10">
                            <div class="check-demo-col">
                                <div class="check-line">
                                    <input type="radio" name="HasSubmitted" id="HasSubmitted" readonly="readonly" class='icheck-me' data-skin="square" data-color="blue" value="true" @(Model.HasSubmitted ? "checked" : "")>
                                    <label class='inline' for="HasSubmitted">Yes</label>
                                </div>
                                <div class="check-line">
                                    <input type="radio" name="HasSubmitted" id="HasSubmitted" readonly="readonly" class='icheck-me' data-skin="square" data-color="blue" value="false" @(Model.HasSubmitted ? "" : "checked")>
                                    <label class='inline' for="HasSubmitted">No</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Position" class="control-label col-sm-2">Title of abstract submitted</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(model => model.SubmissionTitles, new { @class = "form-control", @readonly = "readonly", @id = "SubmissionTitles" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="textfield" class="control-label col-sm-2">Review <span class="validation-span-required">(*)</span></label>
                        <div class="col-sm-10">
                            @Html.DropDownList("Status", DataHelper.GetInstance().GetScholarshipStatusForDropdown(), new { @id = "Status", @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-actions col-sm-offset-2 col-sm-10">
                        <button type="button" onclick="submitForm()" class="btn btn-primary">Lưu Thông Tin</button>
                        <a href='@Url.Action("Index")' class="btn btn-info">Hủy Bỏ</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script>
    function submitForm() {
        if (!validateForm()) {
            bootbox.alert("Cần phải nhập dữ liệu những trường bắt buộc.", function () {
                bootbox.hideAll();
            });
            return false;
        }

        $.blockUI({ message: $('#spinner') });
        var formData = new FormData();
        formData.append("ScholarshipID", $("#ScholarshipID").val());
        formData.append("UserID", $("#UserID").val());
        formData.append("RegistrationNumber", $("#RegistrationNumber").val());
        formData.append("SubmissionNumber", $("#SubmissionNumber").val());
        formData.append("Organization", $("#Organization").val());
        formData.append("Position", $("#Position").val());
        formData.append("DurationOfWork", $("#DurationOfWork").val());
        formData.append("Responsibility", $("#Responsibility").val());
        formData.append("ReasonScholarship", $("#ReasonScholarship").val());
        formData.append("HasSubmitted", $("input[name=HasSubmitted]:checked").val());
        formData.append("SubmissionTitles", $("#SubmissionTitles").val());
        formData.append("Status", $("#Status").find(":selected").val());
        
        $.ajax({
            type: "POST",
            url: '@Url.Action("SaveUpdateMainScholarship", "AdminUser")',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false,
            success: function (response) {
                $.unblockUI();
                bootbox.alert(response.message, function () {
                    bootbox.hideAll();
                });
                //Timeout
                if (response.errorCode == 2) {
                    window.location = "/Administrator/AdminHome/Login";
                }
            },
            error: function (error) {
                $.unblockUI();
                bootbox.alert(error, function () {
                    bootbox.hideAll();
                });
            }
        });
    }

    function validateForm() {
        if ($("#SubmissionNumber").val() == null || $("#SubmissionNumber").val() == "") {
            $("#SubmissionNumber").focus();
            return false;
        }
        if ($("#Organization").val() == null || $("#Organization").val() == "") {
            $("#Organization").focus();
            return false;
        }
        if ($("#Position").val() == null || $("#Position").val() == "") {
            $("#Position").focus();
            return false;
        }
        if ($("#DurationOfWork").val() == null || $("#DurationOfWork").val() == "") {
            $("#DurationOfWork").focus();
            return false;
        }
        if ($("#Responsibility").val() == null || $("#Responsibility").val() == "") {
            $("#Responsibility").focus();
            return false;
        }
        if ($("#ReasonScholarship").val() == null || $("#ReasonScholarship").val() == "") {
            $("#ReasonScholarship").focus();
            return false;
        }
        return true;
    }

    function setControlCss(control) {
        $(control).css({ "background-color": "#ffafb3" });
    }
</script>