apcrshr/apcrshr_site/Controllers/ScholarshipController.cs
using apcrshr_site.Filters;
using apcrshr_site.Helper;
using Site.Core.DataModel.Model;
using Site.Core.DataModel.Response;
using Site.Core.Service.Contract;
using Site.Core.Service.Implementation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace apcrshr_site.Controllers
{
    public class ScholarshipController : BaseController
    {
        private IMainScholarshipService _mainScholarshipService;
        private IYouthScholarshipService _youthScholarshipService;
        private IExperienceService _experienceService;
        private IEducationService _educationService;
        private ITrainingService _trainingService;
        private ILeaderShipService _leadershipService;
        private IPublicationService _publicationService;

        public ScholarshipController()
        {
            this._mainScholarshipService = new MainScholarshipService();
            this._youthScholarshipService = new YouthScholarshipService();
            this._experienceService = new ExperienceService();
            this._educationService = new EducationService();
            this._trainingService = new TrainingService();
            this._leadershipService = new LeaderShipService();
            this._publicationService = new PublicationService();
        }

        //
        // GET: /Scholarship/

        public ActionResult Index()
        {
            return View();
        }

        [UserSessionFilter]
        public ActionResult MainScholarships()
        {
            string sessionId = Session["User-SessionID"].ToString();
            Site.Core.Repository.User _user = SessionUtil.GetInstance.GetUserBySessionID(sessionId);

            FindAllItemReponse<MainScholarshipModel> response = new FindAllItemReponse<MainScholarshipModel>();

            if (_user != null)
            {
                response = _mainScholarshipService.FindByUserID(_user.UserID);
                if (response.Items == null)
                {
                    response.Items = new List<MainScholarshipModel>();
                }
            }
            return View(response.Items);
        }

        [UserSessionFilter]
        public ActionResult UpdateMainScholarship(string scholarshipID)
        {
            FindItemReponse<MainScholarshipModel> response = _mainScholarshipService.FindByID(scholarshipID);
            return View(response.Item);
        }

        [UserSessionFilter]
        
        public ActionResult SaveMainScholarship(MainScholarshipModel scholarship)
        {
            string sessionId = Session["User-SessionID"].ToString();
            Site.Core.Repository.User _user = SessionUtil.GetInstance.GetUserBySessionID(sessionId);

            scholarship.UpdatedBy = _user.UserID;
            scholarship.UpdatedDate = DateTime.Now;
            BaseResponse response = _mainScholarshipService.Update(scholarship);
            ViewBag.Message = response;
            return View("UpdateMainScholarship", scholarship);
        }

        [UserSessionFilter]
        public ActionResult YouthScholarships(string scholarshipID)
        {
            string sessionId = Session["User-SessionID"].ToString();
            Site.Core.Repository.User _user = SessionUtil.GetInstance.GetUserBySessionID(sessionId);

            FindItemReponse<YouthScholarshipModel> response = new FindItemReponse<YouthScholarshipModel>();

            if (_user != null)
            {
                response = _youthScholarshipService.FindByUserID(_user.UserID);
                if (response.Item == null)
                {
                    response.Item = new YouthScholarshipModel();
                }
            }

            //Find experiences
            FindAllItemReponse<ExperienceModel> experiencesResponse = _experienceService.FindByscholarshipID(response.Item.YouthScholarshipID);
            if (experiencesResponse.Items != null && experiencesResponse.Items.Count > 0)
            {
                response.Item.ExperienceTitles = string.Join(",", experiencesResponse.Items.Select(i => i.Organization));
            }
            //Find educations
            FindAllItemReponse<EducationModel> educationsResponse = _educationService.FindByscholarshipID(response.Item.YouthScholarshipID);
            if (educationsResponse.Items != null && educationsResponse.Items.Count > 0)
            {
                response.Item.EducationTitles = string.Join(",", educationsResponse.Items.Select(i => i.MainCourseStudy));
            }
            //Find trainings
            FindAllItemReponse<TrainingModel> trainingsResponse = _trainingService.FindByscholarshipID(response.Item.YouthScholarshipID);
            if (trainingsResponse.Items != null && trainingsResponse.Items.Count > 0)
            {
                response.Item.AdditionalTrainingTitles = string.Join(",", trainingsResponse.Items.Select(i => i.NameOfCourse));
            }
            //Find leadership
            FindAllItemReponse<LeaderShipModel> leadershipsResponse = _leadershipService.FindByscholarshipID(response.Item.YouthScholarshipID);
            if (leadershipsResponse.Items != null && leadershipsResponse.Items.Count > 0)
            {
                response.Item.LeaderShipTitles = string.Join(",", leadershipsResponse.Items.Select(i => i.Organization));
            }
            //Find publication
            FindAllItemReponse<PublicationModel> publicationsResponse = _publicationService.FindByscholarshipID(response.Item.YouthScholarshipID);
            if (publicationsResponse.Items != null && publicationsResponse.Items.Count > 0)
            {
                response.Item.PublicationTitles = string.Join(",", publicationsResponse.Items.Select(i => i.Title));
            }

            return View(response.Item);
        }

        [UserSessionFilter]
        
        public ActionResult SaveYouthScholarship(YouthScholarshipModel scholarship)
        {
            string sessionId = Session["User-SessionID"].ToString();
            Site.Core.Repository.User _user = SessionUtil.GetInstance.GetUserBySessionID(sessionId);

            scholarship.UpdatedBy = _user.UserID;
            scholarship.UpdatedDate = DateTime.Now;
            BaseResponse response = _youthScholarshipService.Update(scholarship);
            ViewBag.Message = response;
            return View("YouthScholarships", scholarship);
        }
    }
}

apcrshr/apcrshr_site/Controllers/UserController.cs
using apcrshr_site.Filters;
using Site.Core.DataModel.Enum;
using Site.Core.DataModel.Model;
using Site.Core.DataModel.Response;
using Site.Core.Service.Contract;
using Site.Core.Service.Implementation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using apcrshr_site.Models;
using Site.Core.Repository;
using apcrshr_site.Helper;
using System.Globalization;
using System.IO;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Text;

namespace apcrshr_site.Controllers
{
    [OutputCache(NoStore = true, Duration = 60, VaryByParam = "*")]
    public class UserController : BaseController
    {
        private static readonly string PAYMENT_TITLE = "Acknowledgement of Payment - Registration for APCRSHR9 - Transaction ID {0}";
        //Third party payment information
        private static readonly string SECURE_SECRET = "CE73CA8FAE51D3D33D56F5D44812B409";
        private static readonly string VIRTUAL_PAYMENT_CLIENT = "https://onepay.vn/vpcpay/vpcpay.op";
        private static readonly string vpc_Version = "2";
        private static readonly string vpc_Command = "pay";
        //Test account
        private static readonly string vpc_AccessCode = "BEB4FDDB";
        private static readonly string vpc_Merchant = "APCRSHR9VN";
        private static readonly string vpc_Locale = "en";
        //Return url
		private static readonly string vpc_ReturnURL = "http://apcrshr9vn.org/User/PaymentReturn";
        //Currency
        private static readonly string FROM_CURRENCY = "USD";
        private static readonly string TO_CURRENCY = "VND";

        private IUserService _userService;
        private IMailingAddressService _mailingService;
        private IPaymentService _paymentService;
        private IUserSubmissionService _userSubmissionService;
        private ILogisticSheduleService _logisticService;
        private ITransactionHistoryService _transaction;

        public UserController()
        {
            this._userService = new UserService();
            this._mailingService = new MailingAddressService();
            this._paymentService = new PaymentService();
            this._userSubmissionService = new UserSubmissionService();
            this._logisticService = new LogisticSheduleService();
            this._transaction = new TransactionHistoryService();
        }


        //
        // GET: /User/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]

        public ActionResult UserLogin(UserModel user)
        {
            if (ModelState.IsValid)
            {
                UserLoginResponse response = _userService.Login(user.UserName, user.Password);
                if (response.ErrorCode == (int)ErrorCode.None)
                {
                    this.Session["User-UserID"] = response.UserId;
                    this.Session["User-SessionID"] = response.SessionId;
                    this.Session["User-UserName"] = response.UserName;
                    return RedirectToAction("Index", "Home");
                }
                ViewBag.Response = response;
            }
            return View("Login");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]

        public ActionResult RegisterUser(UserModel user)
        {
            if (ModelState.IsValid)
            {
                InsertResponse response = new InsertResponse();
                FindItemReponse<UserModel> usernameResponse = _userService.CheckUsername(user.UserName);
                if (usernameResponse.Item != null)
                {
                    response = new InsertResponse
                    {
                        ErrorCode = (int)ErrorCode.Error,
                        Message = Resources.Resource.msg_username_exist
                    };
                    ViewBag.Response = response;
                    return View("Register");
                }
                else
                {
                    FindItemReponse<UserModel> emailResponse = _userService.CheckEmail(user.Email);
                    if (emailResponse.Item != null)
                    {
                        response = new InsertResponse
                        {
                            ErrorCode = (int)ErrorCode.Error,
                            Message = Resources.Resource.msg_email_exist
                        };
                        ViewBag.Response = response;
                        return View("Register");
                    }
                    else
                    {
                        user.UserID = Guid.NewGuid().ToString();
                        user.CreatedDate = DateTime.Now;
                        response = _userService.CreateUser(user);
                        ViewBag.Response = response;
                    }
                }
            }
            return View("Register");
        }

        [HttpGet]
        public ActionResult Logout()
        {
            string sessionId = string.Empty;
            if (this.Session["User-SessionID"] != null)
            {
                sessionId = this.Session["User-SessionID"].ToString();
            }
            if (string.IsNullOrEmpty(sessionId))
            {
                RedirectToAction("Index", "Home");
            }
            BaseResponse response = _userService.Logout(sessionId);
            this.Session["User-SessionID"] = null;
            this.Session["User-UserName"] = null;
            this.Session["User-UserID"] = null;
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [UserSessionFilter]
        public ActionResult ViewProfile()
        {
            if (this.Session["User-UserID"] != null)
            {
                RegistrationModel registration = new RegistrationModel();
                FindItemReponse<UserModel> response = _userService.FindUserByID(Session["User-UserID"].ToString());
                if (response.Item != null)
                {
                    registration.UserID = response.Item.UserID;
                    registration.Title = response.Item.Title;
                    registration.FullName = response.Item.FullName;
                    registration.Sex = response.Item.Sex;
                    registration.Email = response.Item.Email;
                    registration.OtherEmail = response.Item.OtherEmail;
                    registration.DateOfBirth = response.Item.DateOfBirth;
                    registration.Phone = response.Item.PhoneNumber;
                    registration.UserName = response.Item.UserName;
                    registration.MealPreference = response.Item.MealPreference;
                    registration.DisabilityOrTreatment = response.Item.DisabilitySpecialTreatment;
                    registration.Address = response.Item.Address;
                    registration.City = response.Item.City;
                    registration.Country = response.Item.Country;
                    registration.WorkAddress = response.Item.WorkAddress;
                    registration.Organization = response.Item.Organization;

                    //Find abstract
                    FindAllItemReponse<UserSubmissionModel> abstractResponse = _userSubmissionService.FindByUserID(response.Item.UserID);
                    ViewBag.Abstracts = abstractResponse.Items;
                }
                FindItemReponse<LogisticScheduleModel> logisticResponse = _logisticService.FindByUserID(Session["User-UserID"].ToString());
                registration.Logistic = logisticResponse.Item != null ? logisticResponse.Item : new LogisticScheduleModel();
                FindAllItemReponse<MailingAddressModel> mailingResponse = _mailingService.FindMailingAddressByUser(Session["User-UserID"].ToString());
                if (mailingResponse.Items != null)
                {
                    var mailing = mailingResponse.Items.SingleOrDefault();
                    if (mailing != null)
                    {
                        registration.MailingAddressID = mailing.MailingAddressID;
                        registration.ParticipantType = mailing.ParticipantType;
                        registration.YouthConference = mailing.ParticipateYouth;
                        registration.OriginalNationality = mailing.OriginalNationality;
                        registration.CurrentNationality = mailing.CurrentNationality;
                        registration.PassportNumber = mailing.PassportNumber;
                        registration.TypeOfPassport = mailing.TypeOfPassport;
                        registration.Occupation = mailing.Occupation;
                        registration.DateOfPassportIssue = mailing.DateOfPassportIssue;
                        registration.DateOfPassportExpiry = mailing.DateOfPassportExpiry;
                        registration.PassportPhoto1 = mailing.PassportPhoto1;
                        registration.PassportPhoto2 = mailing.PassportPhoto2;
                        registration.PassportPhoto3 = mailing.PassportPhoto3;
                        registration.DetailOfEmbassy = mailing.DetailOfEmbassy;
                        registration.NeedVisaSupport = mailing.NeedVisaSupport;

                        //Get fee
                        int fee = -1;

                        //Find payment
                        FindAllItemReponse<PaymentModel> paymentResponse = _paymentService.FindByUserID(Session["User-UserID"].ToString());

apcrshr/apcrshr_site/Views/Scholarship/MainScholarships.cshtml
@using apcrshr_site.Helper
@model IList<Site.Core.DataModel.Model.MainScholarshipModel>
@{
    ViewBag.Title = "Main Sholarships";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!-- dataTables -->
<link rel="stylesheet" href="~/Areas/Administrator/css/plugins/datatable/TableTools.css">

<!-- New DataTables -->
<script src="~/Areas/Administrator/js/plugins/momentjs/jquery.moment.min.js"></script>
<script src="~/Areas/Administrator/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/Areas/Administrator/js/plugins/datatables/extensions/dataTables.tableTools.min.js"></script>
<script src="~/Areas/Administrator/js/plugins/datatables/extensions/dataTables.colReorder.min.js"></script>
<script src="~/Areas/Administrator/js/plugins/datatables/extensions/dataTables.colVis.min.js"></script>
<script src="~/Areas/Administrator/js/plugins/datatables/extensions/dataTables.scroller.min.js"></script>

<div class="col-sm-9">
    <div class="box box-color box-bordered">
        <div class="box-title">
            <h3>
                <i class="fa fa-magic"></i>
                Main sholarships
            </h3>
        </div>
        <div class="box-content">
            <table class="table table-hover table-nomargin table-bordered dataTable dataTable-column_filter"
                   data-column_filter_types="text,text,select,daterange,null"
                   data-column_filter_dateformat="dd-mm-yy" data-nosort="0" data-checkall="all">
                <thead>
                    <tr>
                        <th>Submission Number</th>
                        <th>Organization</th>
                        <th>Review Status</th>
                        <th class='hidden-1024'>Submitted Date</th>
                        <th class='hidden-480'>Options</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <tr id="@Model[i].ScholarshipID">
                            <td>@Model[i].SubmissionNumber</td>
                            <td>@Model[i].Organization</td>
                            <td>
                                @if (Model[i].Status == (int)Site.Core.DataModel.Enum.ScholarshipStatus.Reviewed)
                                {
                                    <span style="color: blue; font-weight:bold;">@apcrshr_site.Helper.DataHelper.GetInstance().GetScholarshipStatusName(Model[i].Status)</span>
                                }
                                else
                                {
                                    <span style="color: red; font-weight:bold;">@apcrshr_site.Helper.DataHelper.GetInstance().GetScholarshipStatusName(Model[i].Status)</span>
                                }
                                
                            </td>
                            <td class='hidden-1024'>@Model[i].CreatedDate.ToShortDateString()</td>
                            <td class='hidden-480'>
                                <a href='@Url.Action("UpdateMainScholarship", "Scholarship", new { scholarshipID = Model[i].ScholarshipID })' class="btn" rel="tooltip" title="Update">
                                    <i class="fa fa-edit"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

apcrshr/apcrshr_site/Views/Scholarship/UpdateMainScholarship.cshtml
@using apcrshr_site.Helper
@model Site.Core.DataModel.Model.MainScholarshipModel
@{
    ViewBag.Title = "Update main sholarship";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<!-- Tagsinput -->
<link rel="stylesheet" href="~/Areas/Administrator/css/plugins/tagsinput/jquery.tagsinput.css">
<!-- TagsInput -->
<script src="~/Areas/Administrator/js/plugins/tagsinput/jquery.tagsinput.min.js"></script>
<div class="col-sm-9">
    <!--Alert-->
    @if (ViewBag.Message != null)
    {
        Site.Core.DataModel.Response.BaseResponse responseMsg = (Site.Core.DataModel.Response.BaseResponse)ViewBag.Message;
        <br />
        <div class="alert @(responseMsg.ErrorCode == (int)Site.Core.DataModel.Enum.ErrorCode.None ? " alert-info" : " alert-danger")"><a class="close" data-dismiss="alert" href="#">×</a><strong></strong> @responseMsg.Message</div>
    }
    
    <div class="box box-color box-bordered">
        <div class="box-title">
            <h3>
                <i class="fa fa-magic"></i>
                Main sholarship form
            </h3>
        </div>
        <div class="box-content">
            @using (Html.BeginForm("#", "Scholarship", FormMethod.Post, new { @class = "form-horizontal form-validate", @id = "frmMainScholarship", @onsubmit = "onSubmitTrigger()" }))
            {
                
                @Html.HiddenFor(Model => Model.ScholarshipID)
                @Html.HiddenFor(Model => Model.UserID)
                @Html.HiddenFor(Model => Model.SubmissionNumber)
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Registration number <span class="validation-span-required">(*)</span></label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(Model => Model.RegistrationNumber, new { @readonly = "readonly", @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Abstract submission number <span class="validation-span-required">(*)</span></label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(Model => Model.SubmissionNumber, new Dictionary<string, object> {
                                { "class", "form-control" },
                                { "data-rule-required", "true" },
                                { "readonly", "readonly" }
                            })
                    </div>
                </div>
                <div class="form-group">
                    <p style="padding: 10px; text-align: justify;">You have to register and submit abstract before apply for a scholarship. Once you have finished registration form and abstract submission form, the registration number and the abstract submission number will be sent to your email. If you have not registered and submit abstract, please do it <a href='@Url.Action("RegistrationForm", "Registration")'>HERE</a>.</p>
                </div>
                <div class="box-title" style="margin-left: -20px; margin-right: -20px;">
                    <h3>
                        <i class="fa fa-check"></i>
                        SCHOLARSHIP PACKAGE
                    </h3>
                </div>
                <br />
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Please select the scholarship package that you want to apply? <span class="validation-span-required">(*)</span></label>
                    <div class="col-sm-9">
                        <div class="checkbox">
                            <label>
                                <input type="radio" disabled id="ScholarshipPackage" name="ScholarshipPackage" value="Full scholarship: Registration fee, travel, hotel, perdiem" data-rule-required="true" @("Full scholarship: Registration fee, travel, hotel, perdiem".Equals(this.Model.ScholarshipPackage) ? "checked" : "")>&nbsp;Full scholarship: Registration fee, travel, hotel, perdiem<br />
                                <input type="radio" disabled id="ScholarshipPackage" name="ScholarshipPackage" value="Partial scholarship 1: Registration fee, travel" data-rule-required="true" @("Partial scholarship 1: Registration fee, travel".Equals(this.Model.ScholarshipPackage) ? "checked" : "")>&nbsp;Partial scholarship 1: Registration fee, travel<br />
                                <input type="radio" disabled id="ScholarshipPackage" name="ScholarshipPackage" value="Partial scholarship 2: Registration fee, hotel" data-rule-required="true" @("Partial scholarship 2: Registration fee, hotel".Equals(this.Model.ScholarshipPackage) ? "checked" : "")>&nbsp;Partial scholarship 2: Registration fee, hotel<br />
                                <input type="radio" disabled id="ScholarshipPackage" name="ScholarshipPackage" value="Partial scholarship 3: Registration fee" data-rule-required="true" @("Partial scholarship 3: Registration fee".Equals(this.Model.ScholarshipPackage) ? "checked" : "")>&nbsp;Partial scholarship 3: Registration fee
                            </label>
                        </div>
                    </div>
                </div>
                <div class="box-title" style="margin-left: -20px; margin-right: -20px;">
                    <h3>
                        <i class="fa fa-check"></i>
                        WORKING EXPERIENCE
                    </h3>
                </div>
                <br />
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Current organization (Full name) <span class="validation-span-required">(*)</span></label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(Model => Model.Organization, new Dictionary<string, object> {
                                { "class", "form-control" },
                                { "data-rule-required", "true" },
                                { "maxlength", "50" },
                                { "readonly", "readonly" }
                            })
                    </div>
                </div>
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Position <span class="validation-span-required">(*)</span></label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(Model => Model.Position, new Dictionary<string, object> {
                                { "class", "form-control" },
                                { "data-rule-required", "true" },
                                { "readonly", "readonly" }
                            })
                    </div>
                </div>
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Duration of work (number of year) <span class="validation-span-required">(*)</span></label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(Model => Model.DurationOfWork, new Dictionary<string, object> {
                                { "class", "form-control" },
                                { "data-rule-required", "true" },
                                { "data-rule-number", "true" },
                                { "readonly", "readonly" }
                            })
                    </div>
                </div>
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Responsibility relating to Reproductive and Sexual Health and Rights <span class="validation-span-required">(*)</span></label>
                    <div class="col-sm-9">
                        @Html.TextAreaFor(Model => Model.Responsibility, new Dictionary<string, object> {
                                { "class", "form-control" },
                                { "data-rule-required", "true" },
                                { "rows", "3" },
                                { "maxlength", "1000" },
                                { "readonly", "readonly" }
                            })
                    </div>
                </div>
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Why should we provide you a scholarship? <span class="validation-span-required">(*)</span></label>
                    <div class="col-sm-9">
                        @Html.TextAreaFor(Model => Model.ReasonScholarship, new Dictionary<string, object> {
                                { "class", "form-control" },
                                { "data-rule-required", "true" },
                                { "rows", "7" },
                                { "maxlength", "1000" },
                                { "readonly", "readonly" }
                            })
                    </div>
                </div>
                <div class="box-title" style="margin-left: -20px; margin-right: -20px;">
                    <h3>
                        <i class="fa fa-check"></i>
                        ABSTRACT SUBMISSION
                    </h3>
                </div>
                <br />
                <div class="form-group">
                        <label for="textfield" class="control-label col-sm-2">Have you submitted at least 1 abstract for the conference <span class="validation-span-required">(*)</span></label>
                        <div class="col-sm-10">
                            <div class="check-demo-col">
                                <div class="check-line">
                                    <input type="radio" disabled name="HasSubmitted" id="HasSubmitted" class='icheck-me' data-skin="square" data-color="blue" value="true" @(this.Model.HasSubmitted ? "checked" : "")>
                                    <label class='inline' for="HasSubmitted">Yes</label>
                                </div>
                                <div class="check-line">
                                    <input type="radio" disabled name="HasSubmitted" id="HasSubmitted" class='icheck-me' data-skin="square" data-color="blue" value="false" @(this.Model.HasSubmitted ? "" : "checked")>
                                    <label class='inline' for="HasSubmitted">No</label>
                                </div>
                            </div>
                        </div>
                    </div>
                <div class="form-group">
                    <label for="anotherelem" class="control-label col-sm-3">Title of abstract submitted</label>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(Model => Model.SubmissionTitles, new Dictionary<string, object> {
                                { "class", "tagsinput form-control" },
                                { "SubmissionTitles", "SubmissionTitles" },
                                { "readonly", "readonly" }
                            })
                    </div>
                </div>
                <div class="form-actions col-sm-offset-3 col-sm-9">
                    <button disabled type="submit" class="btn btn-primary">Save Changes</button>
                    <a href='@Url.Action("ViewProfile", "User")' class="btn btn-info">Cancel</a>
                </div>
            }
        </div>
    </div>
</div>
<script type="text/javascript">
    // tag-input
    if ($(".tagsinput").length > 0) {
        $('.tagsinput').each(function (e) {
            $(this).tagsInput({
                width: 'auto',
                height: 'auto',
                defaultText: 'add a title'
            });
        });
    }

    function onSubmitTrigger() {
        if ($("#frmMainScholarship").valid()) {
            $.blockUI({ message: $('#spinner') });
        }
    }
</script>