apcrshr/apcrshr_site/Controllers/AbstractController.cs
using apcrshr_site.Filters;
using Site.Core.DataModel.Enum;
using Site.Core.DataModel.Model;
using Site.Core.DataModel.Response;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace apcrshr_site.Controllers
{
    public class AbstractController : BaseController
    {
        //
        // GET: /Abstract/
        [UserSessionFilter]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [UserSessionFilter]
        public ActionResult SubmitAbstract()
        {
            //Allow registration when registration opened
            FindItemReponse<ImportantDeadlineModel> importantDeadlineResponse = _importantDeadlineService.FindImportantDeadlineByType(DeadlineType.Abstract);
            if (importantDeadlineResponse.Item == null)
            {
                return RedirectToAction("AbstractNotAvailable", new { status = 1 });
            }
            else if (importantDeadlineResponse.Item.Deadline < DateTime.Now)
            {
                return RedirectToAction("AbstractNotAvailable", new { status = 2 });
            }
            return View();
        }

        /// <summary>
        /// Display registration status
        /// </summary>
        /// <param name="status">
        /// 1: Abstract is not opened
        /// 2: Abstract is expired
        /// </param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult AbstractNotAvailable(int status)
        {
            ViewBag.Status = status;
            return View();
        }

    }
}

apcrshr/apcrshr_site/Controllers/UserController.cs
using apcrshr_site.Filters;
using Site.Core.DataModel.Enum;
using Site.Core.DataModel.Model;
using Site.Core.DataModel.Response;
using Site.Core.Service.Contract;
using Site.Core.Service.Implementation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using apcrshr_site.Models;
using Site.Core.Repository;
using apcrshr_site.Helper;
using System.Globalization;
using System.IO;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Text;

namespace apcrshr_site.Controllers
{
    [OutputCache(NoStore = true, Duration = 60, VaryByParam = "*")]
    public class UserController : BaseController
    {
        private static readonly string PAYMENT_TITLE = "Acknowledgement of Payment - Registration for APCRSHR9 - Transaction ID {0}";
        //Third party payment information
        private static readonly string SECURE_SECRET = "CE73CA8FAE51D3D33D56F5D44812B409";
        private static readonly string VIRTUAL_PAYMENT_CLIENT = "https://onepay.vn/vpcpay/vpcpay.op";
        private static readonly string vpc_Version = "2";
        private static readonly string vpc_Command = "pay";
        //Test account
        private static readonly string vpc_AccessCode = "BEB4FDDB";
        private static readonly string vpc_Merchant = "APCRSHR9VN";
        private static readonly string vpc_Locale = "en";
        //Return url
		private static readonly string vpc_ReturnURL = "http://apcrshr9vn.org/User/PaymentReturn";
        //Currency
        private static readonly string FROM_CURRENCY = "USD";
        private static readonly string TO_CURRENCY = "VND";

        private IUserService _userService;
        private IMailingAddressService _mailingService;
        private IPaymentService _paymentService;
        private IUserSubmissionService _userSubmissionService;
        private ILogisticSheduleService _logisticService;
        private ITransactionHistoryService _transaction;

        public UserController()
        {
            this._userService = new UserService();
            this._mailingService = new MailingAddressService();
            this._paymentService = new PaymentService();
            this._userSubmissionService = new UserSubmissionService();
            this._logisticService = new LogisticSheduleService();
            this._transaction = new TransactionHistoryService();
        }


        //
        // GET: /User/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]

        public ActionResult UserLogin(UserModel user)
        {
            if (ModelState.IsValid)
            {
                UserLoginResponse response = _userService.Login(user.UserName, user.Password);
                if (response.ErrorCode == (int)ErrorCode.None)
                {
                    this.Session["User-UserID"] = response.UserId;
                    this.Session["User-SessionID"] = response.SessionId;
                    this.Session["User-UserName"] = response.UserName;
                    return RedirectToAction("Index", "Home");
                }
                ViewBag.Response = response;
            }
            return View("Login");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]

        public ActionResult RegisterUser(UserModel user)
        {
            if (ModelState.IsValid)
            {
                InsertResponse response = new InsertResponse();
                FindItemReponse<UserModel> usernameResponse = _userService.CheckUsername(user.UserName);
                if (usernameResponse.Item != null)
                {
                    response = new InsertResponse
                    {
                        ErrorCode = (int)ErrorCode.Error,
                        Message = Resources.Resource.msg_username_exist
                    };
                    ViewBag.Response = response;
                    return View("Register");
                }
                else
                {
                    FindItemReponse<UserModel> emailResponse = _userService.CheckEmail(user.Email);
                    if (emailResponse.Item != null)
                    {
                        response = new InsertResponse
                        {
                            ErrorCode = (int)ErrorCode.Error,
                            Message = Resources.Resource.msg_email_exist
                        };
                        ViewBag.Response = response;
                        return View("Register");
                    }
                    else
                    {
                        user.UserID = Guid.NewGuid().ToString();
                        user.CreatedDate = DateTime.Now;
                        response = _userService.CreateUser(user);
                        ViewBag.Response = response;
                    }
                }
            }
            return View("Register");
        }

        [HttpGet]
        public ActionResult Logout()
        {
            string sessionId = string.Empty;
            if (this.Session["User-SessionID"] != null)
            {
                sessionId = this.Session["User-SessionID"].ToString();
            }
            if (string.IsNullOrEmpty(sessionId))
            {
                RedirectToAction("Index", "Home");
            }
            BaseResponse response = _userService.Logout(sessionId);
            this.Session["User-SessionID"] = null;
            this.Session["User-UserName"] = null;
            this.Session["User-UserID"] = null;
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [UserSessionFilter]
        public ActionResult ViewProfile()
        {
            if (this.Session["User-UserID"] != null)
            {
                RegistrationModel registration = new RegistrationModel();
                FindItemReponse<UserModel> response = _userService.FindUserByID(Session["User-UserID"].ToString());
                if (response.Item != null)
                {
                    registration.UserID = response.Item.UserID;
                    registration.Title = response.Item.Title;
                    registration.FullName = response.Item.FullName;
                    registration.Sex = response.Item.Sex;
                    registration.Email = response.Item.Email;
                    registration.OtherEmail = response.Item.OtherEmail;
                    registration.DateOfBirth = response.Item.DateOfBirth;
                    registration.Phone = response.Item.PhoneNumber;
                    registration.UserName = response.Item.UserName;
                    registration.MealPreference = response.Item.MealPreference;
                    registration.DisabilityOrTreatment = response.Item.DisabilitySpecialTreatment;
                    registration.Address = response.Item.Address;
                    registration.City = response.Item.City;
                    registration.Country = response.Item.Country;
                    registration.WorkAddress = response.Item.WorkAddress;
                    registration.Organization = response.Item.Organization;

                    //Find abstract
                    FindAllItemReponse<UserSubmissionModel> abstractResponse = _userSubmissionService.FindByUserID(response.Item.UserID);
                    ViewBag.Abstracts = abstractResponse.Items;
                }
                FindItemReponse<LogisticScheduleModel> logisticResponse = _logisticService.FindByUserID(Session["User-UserID"].ToString());
                registration.Logistic = logisticResponse.Item != null ? logisticResponse.Item : new LogisticScheduleModel();
                FindAllItemReponse<MailingAddressModel> mailingResponse = _mailingService.FindMailingAddressByUser(Session["User-UserID"].ToString());
                if (mailingResponse.Items != null)
                {
                    var mailing = mailingResponse.Items.SingleOrDefault();
                    if (mailing != null)
                    {
                        registration.MailingAddressID = mailing.MailingAddressID;
                        registration.ParticipantType = mailing.ParticipantType;
                        registration.YouthConference = mailing.ParticipateYouth;
                        registration.OriginalNationality = mailing.OriginalNationality;
                        registration.CurrentNationality = mailing.CurrentNationality;
                        registration.PassportNumber = mailing.PassportNumber;
                        registration.TypeOfPassport = mailing.TypeOfPassport;
                        registration.Occupation = mailing.Occupation;
                        registration.DateOfPassportIssue = mailing.DateOfPassportIssue;
                        registration.DateOfPassportExpiry = mailing.DateOfPassportExpiry;
                        registration.PassportPhoto1 = mailing.PassportPhoto1;
                        registration.PassportPhoto2 = mailing.PassportPhoto2;
                        registration.PassportPhoto3 = mailing.PassportPhoto3;
                        registration.DetailOfEmbassy = mailing.DetailOfEmbassy;
                        registration.NeedVisaSupport = mailing.NeedVisaSupport;

                        //Get fee
                        int fee = -1;

                        //Find payment
                        FindAllItemReponse<PaymentModel> paymentResponse = _paymentService.FindByUserID(Session["User-UserID"].ToString());

apcrshr/apcrshr_site/Views/Shared/_FooterPartialPage.cshtml
<footer>
    <div class="container">
        <div class="row footer-widgets">

            <!-- Start Contact Widget -->
            <div class="col-md-8">
                <div class="footer-widget contact-widget">
                    <h4>Contact info<span class="head-line"></span></h4>
                    <ul>
                        <li><span>Address:</span> Room 503 – 504, E1 Building, 5th Floor, Trung Tu Diplomatic Compound, 6 Dang Van Ngu, Dong Da, Hanoi, Vietnam</li>
                        <li><span>Tel:</span> (+84) 24 37368065</li>
                        <li><span>Fax:</span> (+84) 24 37366265</li>
                        <li><span>Email:</span> secretariat@apcrshr9vn.org</li>
                        <li><span>Website:</span> http://apcrshr9vn.org</li>
                    </ul>
                </div>
            </div>
            <!-- End Contact Widget -->

            <!-- Start Subscribe & Social Links Widget -->
            <div class="col-md-4">
                <div class="footer-widget social-widget">
                    <h4>Follow Us<span class="head-line"></span></h4>
                    <ul class="social-icons">
                        <li>
                            <a target="_blank" class="facebook" href="https://www.facebook.com/APCRSHR9/"><i class="icon-facebook-2"></i></a>
                        </li>
                        <li>
                            <a target="_blank"  class="twitter" href="https://twitter.com/Apcrshr9"><i class="icon-twitter-2"></i></a>
                        </li>
                        <li>
                            <a target="_blank"  class="instagramm" href="https://www.instagram.com/apcrshr9/"><i class="icon-instagramm"></i></a>
                        </li>
                        <li>
                            <a target="_blank" class="linkdin" href="https://www.linkedin.com/company/vietnam-public-health-association"><i class="icon-linkedin-1"></i></a>
                        </li>
                        <li>
                            <a target="_blank" class="youtube" href="https://www.youtube.com/watch?v=NM-FjUhXSX4"><i class="icon-youtube"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Subscribe & Social Links Widget -->

    </div>
</footer>

apcrshr/apcrshr_site/Views/Shared/_FullWidthLayoutPage.cshtml
<!doctype html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><html lang="en" class="no-js"> <![endif]-->
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /><
<head>

    <!-- Basic -->
    <title>@ViewBag.Title</title>

    <!-- Define Charset -->
    <meta charset="utf-8">
    <!-- Responsive Metatag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Page Description and Author -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Content/images/apcrshr.ico">

    <!-- Responsive Metatag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Page Description and Author -->
    <meta name="description" content="html">
    <meta name="author" content="DesignTEAM">


    <!-- Bootstrap CSS  -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.css" type="text/css" media="screen">

    <!-- Revolution Banner CSS -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/settings.css" media="screen" />

    <!-- Vella CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css" media="screen">

    <!-- Responsive CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/responsive.css" media="screen">

    <!-- Css3 Transitions Styles  -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/animate.css" media="screen">

    <!-- Color CSS Styles  -->
    @Styles.Render("~/bundles/css/colors")

    <!-- Fontello Icons CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/fontello.css" media="screen">
    <!--[if IE 7]><link rel="stylesheet" href="~/Content/css/fontello-ie7.css"><![endif]-->
    <!-- Vella JS  -->
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.migrate.js"></script>
    <script type="text/javascript" src="~/Scripts/modernizrr.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.fitvids.js"></script>
    <script type="text/javascript" src="~/Scripts/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/Scripts/nivo-lightbox.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.appear.js"></script>
    <script type="text/javascript" src="~/Scripts/count-to.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.textillate.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.lettering.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.easypiechart.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.parallax.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.themepunch.revolution.min.js"></script>
    <script type="text/javascript" src="~/Scripts/script.js"></script>
    <!--[if IE 8]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

</head>
<body>
    <!-- Container -->
    <div id="container">

        <!-- Start Header -->
        @Html.Partial("_NatigationBarPartialPage")
        <!-- End Header -->

        <!-- Start Page Banner -->
        <div class="page-banner no-subtitle">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h2>@ViewBag.Title</h2>
                    </div>
                    <div class="col-md-6">
                        <ul class="breadcrumbs">
                            <li><a href="/">Home</a></li>
                            <li>@ViewBag.Title</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Page Banner -->

        <!-- Start Content -->
        @RenderBody()
        <!-- End content -->

        <!-- Start Footer -->
        @Html.Partial("_FooterPartialPage")
        <!-- End Footer -->

    </div>
    <!-- End Container -->
    <!-- Go To Top Link -->
    <a href="#" class="back-to-top"><i class="icon-up-open-1"></i></a>

    <div id="loader">
        <div class="spinner">
            <div class="dot1"></div>
            <div class="dot2"></div>
        </div>
    </div>

</body>
</html>

apcrshr/apcrshr_site/Views/Shared/_Layout.cshtml
<!doctype html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><html lang="en" class="no-js"> <![endif]-->
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>

    <!-- Basic -->
    <title>@ViewBag.Title</title>
    <!-- Define Charset -->
    <meta charset="utf-8">
    <!-- Responsive Metatag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Page Description and Author -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="google-site-verification" content="DlwdFUoYAQTpeGiu_lRaoNet9U3CXBNQIqgJMXYUdp8" />
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/Content/images/apcrshr.ico">

    <!-- Responsive Metatag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Page Description and Author -->
    <meta name="description" content="html">
    <meta name="author" content="DesignTEAM">


    <!-- Bootstrap CSS  -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.css" type="text/css" media="screen">

    <!-- Revolution Banner CSS -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/settings.css" media="screen" />

    <!-- Vella CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css" media="screen">

    <!-- Responsive CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/responsive.css" media="screen">

    <!-- Css3 Transitions Styles  -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/animate.css" media="screen">
    <link rel="stylesheet" id='profile-style' href="~/Content/css/profile-style.css" type='text/css' media='all' />
    <!-- Color CSS Styles  -->
    @Styles.Render("~/bundles/css/colors")

    <!-- Fontello Icons CSS Styles  -->
    <link rel="stylesheet" type="text/css" href="~/Content/css/fontello.css" media="screen">
    <!--[if IE 7]><link rel="stylesheet" href="~/Content/css/fontello-ie7.css"><![endif]-->
    <!-- Vella JS  -->
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.migrate.js"></script>
    <script type="text/javascript" src="~/Scripts/modernizrr.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.fitvids.js"></script>
    <script type="text/javascript" src="~/Scripts/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/Scripts/nivo-lightbox.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.appear.js"></script>
    <script type="text/javascript" src="~/Scripts/count-to.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.textillate.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.lettering.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.easypiechart.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.parallax.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.themepunch.revolution.min.js"></script>
    <script type="text/javascript" src="~/Scripts/script.js"></script>
    <!--[if IE 8]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
    <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

</head>
<body>
    
    <!-- Container -->
    <div id="container" class="boxed-page">

        <!-- Start Header -->
        @Html.Partial("_NatigationBarPartialPage")
        <!-- End Header -->
        <!-- Start Page Banner -->
        <div class="page-banner no-subtitle">
            <div class="container">
                <div class="row">
                    <img src="~/Content/images/banner.png" style="width:100%;" />
                </div>
            </div>
            <!--Login button-->
            @if (Session["User-UserName"] == null)
            {
                <a class="main-button login-button" href='@Url.Action("Login", "User")'>Login <i class="icon-right-small"></i></a>
            }
        </div>
        <!-- End Page Banner -->
        <!-- Start Content -->
        <div id="content">
            <div class="container">
                <div class="row sidebar-page">


                    <!-- Start left Sidebar -->
                    <div class="col-md-3 sidebar left-sidebar">

                        <!-- Search Widget -->
                        <div class="widget widget-search">
                            <form action="/Home/Search" method="post" class="form-validate">
                                <input type="search" name="KeySearch" placeholder="Enter Keywords..." data-rule-required="true" />
                                <button class="search-btn" type="submit"><i class="icon-search-1"></i></button>
                            </form>
                        </div>

                        <!-- Categories Widget -->
                        <a class="elemadded responsive-link" href="#">Menu</a>
                        <div class="widget widget-navbar navbar-vertical">
                            @Html.Partial("_PartialLeftMenu")
                        </div>

                    </div>
                    <!-- End left Sidebar -->
                    <!-- Page Content -->
                    <div class="col-md-9 page-content">

                        @RenderBody()

                    </div>
                    <!-- End Page Content-->

                </div>
            </div>
        </div>
        <!-- End Content -->
        <!-- Start Footer -->
        @Html.Partial("_FooterPartialPage")
        <!-- End Footer -->

    </div>
    <!-- End Container -->
    <!-- Go To Top Link -->
    <a href="#" class="back-to-top"><i class="icon-up-open-1"></i></a>

    <div id="loader">
        <div class="spinner">
            <div class="dot1"></div>
            <div class="dot2"></div>
        </div>
    </div>

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/58cf54641d32632565387a7b/default';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->
</body>
</html>

apcrshr/apcrshr_site/Views/Shared/_NatigationBarPartialPage.cshtml
<div class="hidden-header"></div>
<header class="clearfix">

    <!-- Start Top Bar -->
    <div class="top-bar">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                </div>
                <div class="col-md-6">
                    <!-- Start Social Links -->
                    <ul class="social-list">
                        <li>
                            <a target="_blank" class="facebook sh-tooltip" data-placement="bottom" title="Facebook" href="https://www.facebook.com/9thAPCRSHR/"><i class="icon-facebook-2"></i></a>
                        </li>
                        <!--<li>
                            <a class="twitter sh-tooltip" data-placement="bottom" title="Twitter" href="#"><i class="icon-twitter-2"></i></a>
                        </li>
                        <li>
                            <a class="google sh-tooltip" data-placement="bottom" title="Google Plus" href="#"><i class="icon-gplus"></i></a>
                        </li>-->
                        <li>
                            <a target="_blank" class="linkdin sh-tooltip" data-placement="bottom" title="Linkedin" href="https://www.linkedin.com/company/vietnam-public-health-association"><i class="icon-linkedin"></i></a>
                        </li>
                        <li>
                            <a target="_blank" class="youtube sh-tooltip" data-placement="bottom" title="Youtube" href="https://www.youtube.com/c/HoiYTCCVietnamVPHA"><i class="icon-youtube"></i></a>
                        </li>
                    </ul>
                    <!-- End Social Links -->
                </div>
            </div>
        </div>
    </div>
    <!-- End Top Bar -->

</header>

apcrshr/apcrshr_site/Views/Shared/_PartialRightWidget.cshtml
<!--Sidebar-->
<div class="col-md-3 sidebar right-sidebar">

    <!-- Register Now Register -->
    <div class="widget widget-popular-posts">
        <h4></h4>
        <ul class="register">
            <li>
                <a class="main-button" href='@Url.Action("RegistrationForm", "Registration")' style="color: #FFF; font-size: 12px; font-weight: bold; width: 100%; text-align: center;">Register Now</a>
            </li>
            <li>
                <a class="main-button" href='@Url.Action("SubmitAbstract", "Abstract")' style="color: #FFF; font-size: 12px; font-weight: bold; width: 100%; text-align: center;">Abstract Submission</a>
            </li>
        </ul>
    </div>

    <!--Member widget-->
    @if (Session["User-UserName"] != null)
    {
        <div id="categories-3" class="widget widget_categories profile">
            <div class="btn_style bg1">
                <h4>@apcrshr_site.Resources.Resource.text_myProfile</h4>
            </div>
            <div class="profile-box">
                <div class="profile-cover-image">
                    @*<img src="http://api.randomuser.me/0.3/portraits/men/2.jpg" />*@
                </div>
                <div class="profile-picture">
                    <img src="~/Content/images/default-avatar.png" />
                </div>
                <div class="profile-content">
                    <h2>
                        @(Session["User-UserName"].ToString().Length > 10 ? Session["User-UserName"].ToString().Substring(0, 10) + "..." : Session["User-UserName"].ToString())
                    </h2>
                    <div class="row span2" id="btn_action">
                        <a href="@Url.Action("ViewProfile", "User")">@apcrshr_site.Resources.Resource.button_viewProfile</a>
                        <a href='@Url.Action("Logout", "User")'>@apcrshr_site.Resources.Resource.button_logout</a>
                    </div>
                </div>
            </div>
        </div>
    }

    <!-- Important Deadlines widget -->
    <div class="widget widget-popular-posts">
        <h4>@apcrshr_site.Resources.Resource.title_importantDeadline <span class="head-line"></span></h4>
        <ul>
            @{
                IList<Site.Core.DataModel.Model.ImportantDeadlineModel> deadlines = ((apcrshr_site.Controllers.BaseController)this.ViewContext.Controller).GetImportantDeadlines(10);
                if (deadlines != null)
                {
                    foreach (var item in deadlines)
                    {
                        <li class="sh-tooltip" title="Start from @item.StartDate.ToShortDateString() to @item.Deadline.ToShortDateString()">
                            <div class="widget-thumb-icon">
                                <i class="icon-beaker icon-mini-effect icon-effect-1"></i>
                            </div>
                            <div class="widget-content">
                                <h5><a href='#'>@item.Title</a></h5>
                                <span style="Color: #D85D03; font-weight: bold; ">@item.Deadline.ToShortDateString()</span>
                            </div>
                            <div class="clearfix"></div>
                        </li>
                    }
                }
            }
        </ul>
    </div>

    </div>
<!--End sidebar-->