apcrshr/apcrshr_site/Controllers/NewsController.cs
using Site.Core.DataModel.Model;
using Site.Core.DataModel.Response;
using Site.Core.Service.Contract;
using Site.Core.Service.Implementation;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace apcrshr_site.Controllers
{
    public class NewsController : BaseController
    {
        private INewsService _newsService;

        public NewsController()
        {
            this._newsService = new NewsService();
        }

        //
        // GET: /News/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ViewNews(string ActionURL, int pageIndex = 1)
        {
            FindItemReponse<NewsModel> response = _newsService.FindNewsByActionURL(ActionURL);
            FindAllItemReponse<NewsModel> newsReponse = new FindAllItemReponse<NewsModel>();
            List<NewsModel> list = new List<NewsModel>();
            string subActionURL = string.Empty;
            if (response.Item != null)
            {
                list.Add(response.Item);
                FindAllItemReponse<NewsModel> temp = _newsService.GetRelatedNews(response.Item.CreatedDate, Constants.Constants.PAGE_SIZE, pageIndex, culture);
                if (temp.Items != null)
                {
                    list.AddRange(temp.Items);
                    newsReponse.Items = list;
                    newsReponse.Count = temp.Count;
                }
            }
            return View(newsReponse);
        }
    }
}

apcrshr/apcrshr_site/Views/News/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Index</h2>

apcrshr/apcrshr_site/Views/News/ViewNews.cshtml
@using apcrshr_site.Helper
@model Site.Core.DataModel.Response.FindAllItemReponse<Site.Core.DataModel.Model.NewsModel>
@{
    ViewBag.Title = Model.Items != null && Model.Items.Count > 0 ? Model.Items[0].Title : apcrshr_site.Resources.Resource.title_newDetail;
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<div class="col-md-9 page-content">
    @if (Model.Items != null && Model.Items.Count > 0)
    {
        int i = 1;
        
        <div class="blog-post standard-post">
            <!-- Post Content -->
            <div class="post-content-nopadding">
                <h3>@Model.Items[0].Title</h3><br />
                @Html.Raw(Model.Items[0].Contents)
                <br />
                <ul class="post-meta">
                    <li>@Model.Items[0].CreatedDate.ToString("dddd, d MMMM, yyyy", new System.Globalization.CultureInfo(System.Threading.Thread.CurrentThread.CurrentUICulture.Name))</li>
                    <li><a href="#">Posted by</a>, <a href="#">@apcrshr_site.Helper.UserHelper.GetAdminName(Model.Items[0].CreatedBy)</a></li>
                </ul>
            </div>
        </div>

        if (Model.Items.Count > 1)
        {
            <!-- Start related Posts -->
            <div class="latest-posts-classic">

                <h2>@apcrshr_site.Resources.Resource.title_relatedNews</h2><br />

                @for (; i < Model.Items.Count; i++)
                {
                        <!-- Post 1 -->
                    <div class="post-row animated fadeIn delay-01" data-animation="fadeIn" data-animation-delay="01">
                        <div class="left-meta-post">
                            <img class="img-thumbnail image-text" style="float:left; width:150px;" alt="" src="@Model.Items[i].ThumbnailURL">
                        </div>
                        <h3 class="post-title"><a href='@Url.Action("ViewNews", "News", new { ActionURL = @Model.Items[i].ActionURL })'>@Model.Items[i].Title</a></h3>
                        <div class="post-content">
                            <p>@Model.Items[i].ShortContent <a class="read-more" href='@Url.Action("ViewNews", "News", new { ActionURL = Model.Items[i].ActionURL })'>Read More</a></p>
                        </div>
                    </div>
                }
            </div>
            <!-- End Latest Posts -->
        }
    }
    <br />
    <!-- Start Pagination -->
    <div id="pagination">
        @Html.PagingUtil("ViewNews", "News", Url.RequestContext.RouteData.Values.Where(v => v.Key.Equals("ActionURL")).SingleOrDefault().Value.ToString(), Model.Count, apcrshr_site.Constants.Constants.PAGE_SIZE,
                Url.RequestContext.RouteData.Values.Where(v => v.Key.Equals("pageIndex")).SingleOrDefault())
    </div>
    <!-- End Pagination -->

</div>